config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'comments/create'

  resources :lists, only: %i(new create destroy) do
    resources :tasks, only: :show do
      resources :comments, only: :create
    end
  end

  root 'lists#index'
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :team
  has_many :tasks, dependent: :destroy
  validates :name, presence: true

  def client_id
    @client_id ||= SecureRandom.uuid
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  include CableReady::Broadcaster

  def index
    @lists = current_team.lists
    @new_task ||= Task.new
  end

  def new
    cable_ready[ListsChannel].insert_adjacent_html(
      selector: "#lists",
      html: render_to_string(partial: "lists/form", locals: { list: List.new })
    )
    cable_ready.broadcast_to(current_user)
  end

  def create
    @list = current_user.team.lists.new(list_params)

    if @list.save
      cable_ready[ListsChannel].remove(
        selector: "#list-#{params.dig(:list, :client_id)}"
      ).broadcast_to(current_user)
      cable_ready[TeamChannel].insert_adjacent_html(
        selector: "#lists",
        position: "beforeend",
        html: render_to_string(@list, assigns: { new_task: Task.new })
      ).broadcast_to(current_user.team)
    else
      cable_ready[ListsChannel].morph(
        selector: "#list-#{params.dig(:list, :client_id)}",
        html: render_to_string(partial: "lists/form", locals: { list: @list })
      )
      cable_ready.broadcast_to(current_user)
    end
  end

  def destroy
    @list = current_team.lists.find(params[:id])
    @list.destroy!
    cable_ready[ListChannel].remove(selector: dom_id(@list))
    cable_ready.broadcast_to(@list)
  end

  private

  def list_params
    params.require(:list).permit(:name)
  end
end

app/helpers/list_helper.rb
module ListHelper
end

app/views/lists/_form.html.erb
<div class="card mb-3" id="list-<%= list.client_id %>">
  <div class="card-header">
    New list
  </div>

  <div class="card-body">
    <%= bootstrap_form_with model: list, data: { remote: true } do |form| %>
      <%= form.hidden_field :client_id %>
      <%= form.text_field :name %>
      <%= form.primary %>
    <% end %>
  </div>
</div>

app/views/lists/_list.html.erb
<div class="row my-3" data-controller="list" data-list-id="<%= list.id %>" id="<%= dom_id(list) %>" data-reflex-root="#<%= dom_id(list) %>">
  <div class="col">
    <div class="card">
      <div class="card-header d-flex justify-content-between">
        <%= list.name %>
        <%= link_to "Delete", list_path(list), method: :delete, class: "text-danger", remote: true, data: { confirm: "Are you sure you want to delete  \"#{list.name}\"?" } %>
      </div>
      <div class="card-body p-0">
        <div class="list-group list-group-flush" data-list-target="tasks" id="incomplete-tasks">
          <%= render list.tasks.incomplete, team: current_team %>
        </div>
        <div class="list-group list-group-flush border-top" id="complete-tasks">
          <%= render list.tasks.complete, team: current_team %>
        </div>
        <span class="p-3 text-muted <%= "d-none" if list.tasks.any? %>" id="no-tasks">No tasks</span>
      </div>
      <div class="card-footer border-0 align-items-center">
        <%= bootstrap_form_with model: @new_task, url: '', layout: :inline, data: { reflex: 'submit->List#create_task', list_id: list.to_sgid.to_s, list_target: 'form' } do |form| %>
            <%= form.text_field :name, skip_label: true, wrapper_class: 'flex-fill mr-2', class: 'w-100', placeholder: 'What needs to be done?' %>
            <%= form.submit 'Add task' %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lists/index.html.erb
<div class="my-3">
  <%= link_to "New list", new_list_path, class: "btn btn-primary", remote: true %>
</div>

<div id="lists">
  <%= render @lists %>
</div>