config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'comments/create'

  resources :lists, only: %i(new create destroy) do
    resources :tasks, only: :show do
      resources :comments, only: :create
    end
  end

  root 'lists#index'
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :commentable, polymorphic: true

  validates :body, presence: true

  delegate :name, to: :user, prefix: true
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  include CableReady::Broadcaster

  def create
    @list = current_team.lists.find(params[:list_id])
    @task = @list.tasks.find(params[:task_id])
    @comment = @task.comments.new(comment_params)

    if @comment.save
      cable_ready[TaskChannel].insert_adjacent_html(
        selector: '#comments',
        html: render_to_string(@comment)
      )

      cable_ready[TaskChannel].outer_html(
        selector: "#new-comment",
        html: render_to_string(partial: "comments/form", locals: { new_comment: Comment.new })
      )
    else
      cable_ready[TaskChannel].outer_html(
        selector: "#new-comment",
        html: render_to_string(partial: "comments/form", locals: { new_comment: @comment }),
        focus_selector: "#comment-body"
      )
    end

    cable_ready.broadcast_to(@task)
  end

  private

  def comment_params
    params.require(:comment).permit(:body).merge(user: current_user)
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="card my-3">
  <div class="card-header">
    <%= comment.user_name %>  
  </div>

  <div class="card-body">
    <%= comment.body %>
  </div>
</div>

app/views/comments/_form.html.erb
<div class="card" id="new-comment">
  <div class="card-header">
    New comment
  </div>
  
  <div class="card-body">
    <%= bootstrap_form_with model: new_comment, url: list_task_comments_path(@task.list, @task) do |form| %>
      <%= form.text_area :body, skip_label: true, id: "comment-body" %>
      <%= form.primary %>
    <% end %>
  </div>
</div>