config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  get 'comments/create'

  resources :lists, only: %i(new create destroy) do
    resources :tasks, only: :show do
      resources :comments, only: :create
    end
  end

  root 'lists#index'
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :list
  belongs_to :creator, class_name: 'User'
  belongs_to :assignee, class_name: 'User', optional: true
  belongs_to :completer, class_name: "User", optional: true

  has_many :comments, -> { order(created_at: :asc) }, as: :commentable

  validates :name, presence: true

  scope :incomplete, -> { where(completed_at: nil).order(position: :asc) }
  scope :complete, -> { where.not(completed_at: nil).order(updated_at: :asc) }

  acts_as_list scope: [:list_id, completed_at: nil], top_of_list: 0

  delegate :name, to: :assignee, prefix: true, allow_nil: true
  delegate :name, to: :completer, prefix: true, allow_nil: true

  def complete?
    completed_at.present?
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @list = current_team.lists.find(params[:list_id])
    @task = @list.tasks.includes(:comments).find(params[:id])
    @new_comment = Comment.new
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_task.html.erb
<div id="<%= dom_id(task) %>" class="list-group-item d-flex justify-content-between <%= 'incomplete' unless task.complete? %>" data-controller="task" data-id="<%= task.to_sgid.to_s %>" data-task-incomplete-class="incomplete">
  <div class="custom-control custom-checkbox" data-task-target="checkbox">
    <input type="checkbox" class="custom-control-input" id="<%= dom_id(task) %>_checkbox" data-reflex="change->TaskReflex#toggle" data-id="<%= task.to_sgid.to_s %>" <%= 'checked' if task.complete? %>>
    <label for="<%= dom_id(task) %>_checkbox" class="custom-control-label">
      <% if task.complete? %>
        <del>
          <%= task.name %>
          <% if task.completer %>
            <span class="text-muted">Completed by <%= task.completer_name %></span>
          <% end %>  
        </del>
      <% else %>
        <%= task.name %>
        <span class="text-muted" id="task-<%= task.id %>-assignee"><%= task.assignee_name %></span>
      <% end %>
    </label>
  </div>
  
  <div class="collapse mt-2" id="collapse-<%= task.id %>" data-task-target="collapse">
    <%= bootstrap_form_with model: task, url: '', layout: :inline, html: { class: 'mb-2' }, data: { reflex: "submit->Task#update", id: task.to_sgid.to_s } do |form| %>
      <%= form.text_field :name, skip_label: true, class: 'mr-2', id: "task_name_#{task.id}" %>
      <%= form.primary 'update' %>
    <% end %>
    
    <%= select_tag :assignee, options_from_collection_for_select(team.users, :id, :name, task.assignee_id), prompt: "Assign user", class: "custom-select", data: { reflex: "change->Task#assign", id: task.to_sgid.to_s } %>
  </div>

  <div class="d-flex align-items-center">
    <%= link_to list_task_path(task.list, task), class: "mr-2" do %>
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-secondary" fill="none" viewBox="0 0 24 24" stroke="currentColor" height="24" width="24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M7 8h10M7 12h4m1 8l-4-4H5a2 2 0 01-2-2V6a2 2 0 012-2h14a2 2 0 012 2v8a2 2 0 01-2 2h-3l-4 4z" />
      </svg>
    <% end %>
    
    <a href="#collapse-<%= task.id %>" data-toggle="collapse" class="mr-2">
      <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6 text-primary" fill="none" viewBox="0 0 24 24" stroke="currentColor" height="24" width="24">
        <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
      </svg>
    </a>

    <svg 
      xmlns="http://www.w3.org/2000/svg" 
      class="h-6 w-6 text-danger" 
      fill="none" 
      viewBox="0 0 24 24" 
      stroke="currentColor" 
      height="24" 
      width="24"
      data-action="click->task#destroy" 
      data-id="<%= task.to_sgid.to_s %>" 
      style="cursor: pointer"
    >
      <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M6 18L18 6M6 6l12 12" />
    </svg>
  </div>
</div>

app/views/tasks/show.html.erb
<h1 class="my-3"><%= @task.name %></h1>

<% if @task.assignee %>
  <p class="text-muted">Assigned to <%= @task.assignee_name %></p>
<% end %>

<% if @task.complete? %>
  <p class="text-muted">Completed by <%= @task.completer_name %></p>
<% end %>

<%= link_to "Back to list", root_path %>

<hr/>

<h3>Comments</h3>

<div id="comments" data-controller="comments" data-comments-task-id="<%= @task.id %>">
  <%= render @task.comments %>
</div>

<%= render "comments/form", new_comment: @new_comment %>